//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleEmailContent
    {
        public int Email_id { get; set; }
        public string Email_Code { get; set; }
        public string Subject { get; set; }
        public string RMA { get; set; }
        public string Reference { get; set; }
        public string Date { get; set; }
        public string Dear { get; set; }
        public string Email_text { get; set; }
        public string Footer { get; set; }
        public string Signature { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public string To { get; set; }
        public Nullable<int> LanguageID { get; set; }
    }
}
