//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    
    public partial class sp_GetArchiveGriddata_Result1
    {
        public int Case { get; set; }
        public string priority { get; set; }
        public string Status { get; set; }
        public string Company { get; set; }
        public string Service_Reason { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ID { get; set; }
        public string File { get; set; }
        public Nullable<System.DateTime> Last_Modified { get; set; }
        public int Request_id { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<int> Request_id1 { get; set; }
        public Nullable<int> Email_Sent { get; set; }
        public Nullable<System.DateTime> Email_date { get; set; }
        public string Confirmation { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string CustomerNumber_FrmSheet { get; set; }
        public string CustomerNumber_Org { get; set; }
        public string OrginalOrderNumber { get; set; }
        public string Waranty { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string product { get; set; }
        public Nullable<double> Orignal_Quantity { get; set; }
        public Nullable<int> InspectionID { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> Department { get; set; }
        public string Operator { get; set; }
        public string Complaint { get; set; }
        public Nullable<int> ServiceTask { get; set; }
        public Nullable<int> Diagnosis { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Description { get; set; }
        public string createRp { get; set; }
        public string ReportDone { get; set; }
        public string Create8DReport { get; set; }
        public string report8DDone { get; set; }
        public Nullable<int> Email_Sent1 { get; set; }
        public Nullable<System.DateTime> Email_date1 { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public string cname { get; set; }
        public string address { get; set; }
        public string Country { get; set; }
        public string street { get; set; }
        public string Zipcode { get; set; }
        public string company1 { get; set; }
        public string CustomerRefNo { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Dep_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Company_ID1 { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public string Reason1 { get; set; }
        public Nullable<int> DiagnosisID { get; set; }
        public string Diagnosis1 { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<int> Company_ID2 { get; set; }
        public Nullable<int> DiagnosisCatID { get; set; }
        public string Categories { get; set; }
        public Nullable<bool> isDelete1 { get; set; }
        public Nullable<int> Completion_id { get; set; }
        public Nullable<int> request_id2 { get; set; }
        public string order_number { get; set; }
        public string credite_note_number { get; set; }
        public string Disposal { get; set; }
        public Nullable<bool> Evaluation_Request { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> Professional_Competence { get; set; }
        public Nullable<int> Reaction_Time { get; set; }
        public string Kindness { get; set; }
        public string Text { get; set; }
        public Nullable<int> Email_Sent2 { get; set; }
        public Nullable<System.DateTime> Email_date2 { get; set; }
    }
}
