//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Solution
    {
        public int solution_id { get; set; }
        public int request_id { get; set; }
        public string statement { get; set; }
        public string Notes { get; set; }
        public string reminder1 { get; set; }
        public string reminder2 { get; set; }
        public Nullable<int> Email_Sent { get; set; }
        public Nullable<System.DateTime> Email_date { get; set; }
    }
}
