//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Completion
    {
        public int Completion_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public string order_number { get; set; }
        public string credite_note_number { get; set; }
        public string Disposal { get; set; }
        public Nullable<bool> Evaluation_Request { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> Professional_Competence { get; set; }
        public Nullable<int> Reaction_Time { get; set; }
        public string Kindness { get; set; }
        public string Text { get; set; }
        public Nullable<int> Email_Sent { get; set; }
        public Nullable<System.DateTime> Email_date { get; set; }
    }
}
