//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SampleDepartments
    {
        public int deparmentID { get; set; }
        public string DepartName { get; set; }
        public string Email { get; set; }
        public int LanguageID { get; set; }
    }
}
