//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SolutionOptions
    {
        public int option_id { get; set; }
        public int solution_id { get; set; }
        public int request_id { get; set; }
        public string Options { get; set; }
        public double price { get; set; }
        public Nullable<bool> decision { get; set; }
    }
}
