//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int Customer_id { get; set; }
        public string cname { get; set; }
        public string address { get; set; }
        public string Country { get; set; }
        public string street { get; set; }
        public string Zipcode { get; set; }
        public string company { get; set; }
        public string CustomerRefNo { get; set; }
        public Nullable<int> Company_ID { get; set; }
    }
}
