//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Inspection
    {
        public int InspectionID { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> Department { get; set; }
        public string Operator { get; set; }
        public string Complaint { get; set; }
        public Nullable<int> ServiceTask { get; set; }
        public Nullable<int> Diagnosis { get; set; }
        public Nullable<int> Reason { get; set; }
        public string Description { get; set; }
        public string createRp { get; set; }
        public string ReportDone { get; set; }
        public string Create8DReport { get; set; }
        public string report8DDone { get; set; }
        public Nullable<int> Email_Sent { get; set; }
        public Nullable<System.DateTime> Email_date { get; set; }
    }
}
