//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Diagnosis
    {
        public int DiagnosisID { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> Language { get; set; }
    }
}
