//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Departments
    {
        public int DepartmentID { get; set; }
        public string Dep_Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<int> LanguageID { get; set; }
    }
}
