//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ServiceTask
    {
        public int DiagnosisCatID { get; set; }
        public string Categories { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> LangID { get; set; }
    }
}
