//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace css.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Company
    {
        public int Company_id { get; set; }
        public string Comapany_Name { get; set; }
        public string Address { get; set; }
        public string Phone_Num { get; set; }
        public string EvaluationLink { get; set; }
        public string Liscense { get; set; }
        public string LisceneExpiryDate { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
